CREATE TABLE task
(
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    status TEXT ,
    description TEXT,
    priority INT,
    project_id BIGINT,
    FOREIGN KEY (project_id) REFERENCES project (id)
)

--
-- CREATE TABLE task
-- (
--     id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     name        VARCHAR(255),
--     description VARCHAR(255),
--     project_id  BIGINT,
--     CONSTRAINT pk_task PRIMARY KEY (id)
-- );
--
-- ALTER TABLE task
--     ADD CONSTRAINT FK_TASK_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);